"use client";
import {Bell,Menu,Search,ShieldCheck,X} from "lucide-react";
import Link from "next/link";
import {useEffect,useState} from "react";
import Sidebar from "./Sidebar";
import {authApi} from "@/services/api";

type Profile={username?:string;first_name?:string;last_name?:string;role?:string;email?:string};
const roleLabel=(role?:string)=>({ADMIN:"Administrator",POLICE_OFFICER:"Police Officer",INVESTIGATOR:"Investigation Officer",LEGAL_OFFICER:"Legal Officer",NORMAL_USER:"User"}[role||""]||role||"User");
const displayName=(u:Profile)=>`${u.first_name||""} ${u.last_name||""}`.trim()||u.username||u.email||"User";
const initials=(u:Profile)=>{const n=displayName(u).trim().split(/\s+/).filter(Boolean);return (n.length>1?n[0][0]+n[n.length-1][0]:n[0]?.slice(0,2)||"US").toUpperCase()};
export default function Header(){
 const [open,setOpen]=useState(false); const [user,setUser]=useState<Profile>({});
 useEffect(()=>{let mounted=true; const load=async()=>{try{const cached=localStorage.getItem("sddms_user"); if(cached&&mounted) setUser(JSON.parse(cached));}catch{} try{const r:any=await authApi.me(); const fresh=(r?.data??r) as Profile; if(mounted){setUser(fresh); localStorage.setItem("sddms_user",JSON.stringify(fresh));}}catch{}}; load(); return()=>{mounted=false}},[]);
 const name=displayName(user); const role=roleLabel(user.role);
 return <><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200/80 bg-white/90 px-3 backdrop-blur sm:px-6"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setOpen(true)} className="rounded-xl border border-slate-200 p-2 text-slate-600 lg:hidden"><Menu size={19}/></button><div className="flex items-center gap-2 font-bold text-navy lg:hidden"><ShieldCheck size={19}/>SDDMS</div><Link href="/dashboard/search" className="relative hidden md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><span className="block w-[min(34vw,360px)] rounded-xl border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm text-slate-400">Search cases, documents, evidence…</span></Link></div><div className="flex items-center gap-2"><Link href="/dashboard/ai" className="hidden rounded-xl bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700 sm:flex">AI Assistant</Link><button className="relative rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell size={17}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-red-500"/></button><Link href="/dashboard/settings" className="flex min-w-0 items-center gap-2 rounded-xl border border-slate-200 px-2 py-1.5"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-blue-100 text-xs font-bold text-blue-700">{initials(user)}</div><div className="hidden min-w-0 text-left sm:block"><p className="max-w-40 truncate text-xs font-semibold">{name}</p><p className="max-w-40 truncate text-[10px] text-slate-400">{role}</p></div></Link></div></header>{open&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-slate-950/40" onClick={()=>setOpen(false)}/><div className="absolute inset-y-0 left-0 w-[86%] max-w-sm animate-slide-in"><div className="relative h-full"><button onClick={()=>setOpen(false)} className="absolute right-3 top-4 z-10 rounded-lg bg-white p-2 text-slate-500"><X size={18}/></button><Sidebar mobile onNavigate={()=>setOpen(false)}/></div></div></div>}</>}
