"use client";
import Link from "next/link"; import {usePathname} from "next/navigation"; import {LayoutDashboard,FolderKanban,FileText,Search,ShieldCheck,Users,ClipboardList,Settings,LogOut,Database,BrainCircuit,Scale,PackageSearch,MessageSquareWarning,LockKeyhole,UserRoundCheck} from "lucide-react"; import {useEffect,useState} from "react"; import {authApi} from "@/services/api";
const staffItems=[
 ["/dashboard","Dashboard",LayoutDashboard], ["/dashboard/cases","Cases",FolderKanban], ["/dashboard/documents","Documents",FileText], ["/dashboard/evidence","Evidence",Database], ["/dashboard/investigations","Investigations",PackageSearch], ["/dashboard/complaints","Complaints",MessageSquareWarning], ["/dashboard/legal","Legal & Court",Scale], ["/dashboard/ai","AI Intelligence",BrainCircuit], ["/dashboard/search","Advanced search",Search], ["/dashboard/audit","Audit logs",ClipboardList]
] as const;
const normalItems=[["/dashboard","My Portal",LayoutDashboard],["/dashboard/complaints","My Complaints",MessageSquareWarning]] as const;
export default function Sidebar({mobile=false,onNavigate}:{mobile?:boolean;onNavigate?:()=>void}){
 const path=usePathname(); const [role,setRole]=useState("");
 useEffect(()=>{let mounted=true;const load=async()=>{try{const raw=localStorage.getItem("sddms_user");if(raw){const u=JSON.parse(raw);if(mounted)setRole(u?.role||"")}}catch{} try{const r:any=await authApi.me();const u=r?.data??r;if(mounted){setRole(u?.role||"");localStorage.setItem("sddms_user",JSON.stringify(u))}}catch{}};load();return()=>{mounted=false}},[]);
 const isNormal=role==="NORMAL_USER"; const items=isNormal?normalItems:staffItems;
 return <aside className={`${mobile?"flex w-full":"hidden w-64 lg:flex"} shrink-0 flex-col border-r border-slate-200 bg-white`}><div className="flex h-20 items-center gap-3 border-b border-slate-100 px-5"><div className="rounded-xl bg-navy p-2 text-white"><ShieldCheck size={22}/></div><div><p className="font-bold text-navy">Secure DMS</p><p className="text-[10px] uppercase tracking-wider text-slate-400">Law & investigation</p></div></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{items.map(([href,label,Icon])=><Link onClick={onNavigate} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-all ${path===href||path.startsWith(`${href}/`)?"bg-blue-50 text-blue-700 shadow-sm":"text-slate-600 hover:bg-slate-50 hover:text-slate-900"}`}><Icon size={17}/>{label}</Link>)}{!isNormal&&<div className="pt-3"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Administration</p>{role==="ADMIN"&&<><Link onClick={onNavigate} href="/dashboard/admin" className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition-all ${path.startsWith("/dashboard/admin")?"bg-navy text-white shadow-sm":"text-slate-700 hover:bg-slate-50"}`}><LockKeyhole size={17}/>Admin Control Center</Link><Link onClick={onNavigate} href="/dashboard/users" className={`mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-all ${path.startsWith("/dashboard/users")?"bg-blue-50 text-blue-700":"text-slate-600 hover:bg-slate-50"}`}><Users size={17}/>Users & roles</Link></>}</div>}{isNormal&&<div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="flex items-center gap-2 text-blue-700"><UserRoundCheck size={17}/><span className="text-xs font-bold">Restricted portal</span></div><p className="mt-2 text-xs leading-5 text-blue-700/80">Only your complaints and their status are available here.</p></div>}</nav><div className="border-t border-slate-100 p-3"><Link onClick={onNavigate} href="/dashboard/settings" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-50"><Settings size={17}/>Settings</Link><Link onClick={()=>{localStorage.removeItem("sddms_access_token");localStorage.removeItem("sddms_user");onNavigate?.()}} href="/login" className="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-red-600 hover:bg-red-50"><LogOut size={17}/>Sign out</Link></div></aside>
}
